### ISSUE TITLE
OOM in `set_module_tensor_to_device`

### ISSUE THREAD

**Issue by johnPertoft** [huggingface/accelerate#965]
### System Info

```Shell
- `Accelerate` version: 0.15.0.dev0 (9b7ef96)
- Platform: Linux-4.19.0-23-cloud-amd64-x86_64-with-glibc2.35
- Python version: 3.10.6
- Numpy version: 1.23.5
- PyTorch version (GPU?): 1.13.1+cu117 (True)
- `Accelerate` default config:
        Not found
```

### Information

- [ ] The official example scripts
- [X] My own modified scripts

### Tasks

- [ ] One of the scripts in the examples/ folder of Accelerate or an officially supported `no_trainer` script in the `examples` folder of the `transformers` repo (such as `run_no_trainer_glue.py`)
- [X] My own task or dataset (give details below)

### Reproduction

Run this script

```python
# flake8: noqa
# type: ignore

import time

import torch
from accelerate import init_empty_weights
from accelerate import load_checkpoint_and_dispatch
from huggingface_hub import snapshot_download

from transformers import AutoConfig
from transformers import AutoModelForCausalLM
from transformers import GPTNeoXTokenizerFast

model_path = snapshot_download("EleutherAI/gpt-neox-20b")
tokenizer = GPTNeoXTokenizerFast.from_pretrained(model_path)

prompt = "GPTNeoX20B is a 20B-parameter autoregressive Transformer model developed by EleutherAI."
inputs = tokenizer(prompt, return_tensors="pt")
inputs = inputs.to("cuda")

print("Creating empty model")
config = AutoConfig.from_pretrained(model_path)
tokenizer = GPTNeoXTokenizerFast.from_pretrained(model_path)
with init_empty_weights():
    model = AutoModelForCausalLM.from_config(config)

print("Loading checkpoint")
model = load_checkpoint_and_dispatch(
    model,
    checkpoint=model_path,
    device_map="auto",
    no_split_module_classes=["GPTNeoXLayer"],
    offload_folder="/tmp/gpt-neox-20b-offload-accelerate",
)

for k, v in model.hf_device_map.items():
    print(k, v)

print("Running forward pass")
with torch.no_grad():
    start = time.perf_counter()
    outputs = model(**inputs)
    end = time.perf_counter()

print(end - start)
```

On an A100 40gb this gave me an OOM error on the last checkpoint shard for this model. These checkpoints have all the tensors already mapped to gpu when loading it.
```
Traceback (most recent call last):
  File "/workspaces/ark-language-models/.experimental/run-large-model/repro.py", line 29, in <module>
    model = load_checkpoint_and_dispatch(
  File "/workspaces/ark-language-models/.venv/lib/python3.10/site-packages/accelerate/big_modeling.py", line 400, in load_checkpoint_and_dispatch
    load_checkpoint_in_model(
  File "/workspaces/ark-language-models/.venv/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 718, in load_checkpoint_in_model
    set_module_tensor_to_device(model, param_name, param_device, value=param, dtype=dtype)
  File "/workspaces/ark-language-models/.venv/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 129, in set_module_tensor_to_device
    value = value.to(old_value.dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.15 GiB (GPU 0; 39.41 GiB total capacity; 37.26 GiB already allocated; 1.02 GiB free; 37.85 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

I think the issue is that the dtype cast allocates a new tensor which if this tensor is already on the gpu might cause an OOM. One fix is to make sure all the tensors are on cpu first when loading the checkpoint. Another is to change the cast so that it happens as the tensor is moved to the designated device instead.

### Expected behavior

```Shell
It shouldn't result in an OOM here.
```

**Comment by johnPertoft** [comment]
The script works fine on a T4 gpu so I guess it's just down to the device mapping that was generated in my case for the A100. But it should still be avoidable I think.

**Comment by johnPertoft** [comment]
Another fix is to just set the dtype when moving the tensor to the designated device instead.

**Comment by sgugger** [comment]
It's possible this was linked to the bug fixed by #983. Could you try again?

**Comment by johnPertoft** [comment]
Tested on `7e4136164e1a4b26299d9eeead28bc6d1229f7cf` now, and I get the same OOM error still.
